// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl52Hf07TotUNr_qGDyo6b8zcQF8vZ9T8',
    appId: '1:980083554601:web:36b9c57091c26b9f871f38',
    messagingSenderId: '980083554601',
    projectId: 'farm-voice-01',
    authDomain: 'farm-voice-01.firebaseapp.com',
    storageBucket: 'farm-voice-01.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvW3t7GO9yu3yCjGkL13bAU7CF3bu1LvU',
    appId: '1:980083554601:android:a1897e1652992c39871f38',
    messagingSenderId: '980083554601',
    projectId: 'farm-voice-01',
    storageBucket: 'farm-voice-01.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-DH9EnL-K4oA1BLaPcFlMgNL09h-VABo',
    appId: '1:980083554601:ios:f24e231a111bb6d8871f38',
    messagingSenderId: '980083554601',
    projectId: 'farm-voice-01',
    storageBucket: 'farm-voice-01.firebasestorage.app',
    iosBundleId: 'com.example.kisanAlert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC-DH9EnL-K4oA1BLaPcFlMgNL09h-VABo',
    appId: '1:980083554601:ios:f24e231a111bb6d8871f38',
    messagingSenderId: '980083554601',
    projectId: 'farm-voice-01',
    storageBucket: 'farm-voice-01.firebasestorage.app',
    iosBundleId: 'com.example.kisanAlert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl52Hf07TotUNr_qGDyo6b8zcQF8vZ9T8',
    appId: '1:980083554601:web:1c02126f179f462f871f38',
    messagingSenderId: '980083554601',
    projectId: 'farm-voice-01',
    authDomain: 'farm-voice-01.firebaseapp.com',
    storageBucket: 'farm-voice-01.firebasestorage.app',
  );
}
